heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls:
    - https://elasticsearch:9200
    - https://kibana:5601
  ssl:
    certificate_authorities: ["/usr/share/heartbeat/certs/ca/ca.crt"]

- type: icmp
  schedule: '@every 5s'
  hosts:
    - elasticsearch
    - kibana

processors:
- add_cloud_metadata:

output.elasticsearch:
  hosts: ['elasticsearch:9200']
  protocol: "https"
  username: elastic
  # Read PW from heartbeat.keystore
  password: "${ELASTIC_PASSWORD}"
  ssl.certificate_authorities: ["/usr/share/heartbeat/certs/ca/ca.crt"]

setup.kibana:
  host: "https://kibana:5601"
  username: elastic
  password: "${ELASTIC_PASSWORD}"
  protocol: "https"
  ssl.enabled: true
  ssl.certificate_authorities: ["/usr/share/heartbeat/certs/ca/ca.crt"]
