filebeat.config:
  prospectors:
    path: ${path.config}/prospectors.d/*.yml
    reload.enabled: false
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

processors:
- add_cloud_metadata:

output.elasticsearch:
  hosts: ['elasticsearch:9200']
  protocol: "https"
  username: elastic
  # Read PW from filebeat.keystore
  password: "${ELASTIC_PASSWORD}"
  ssl.certificate_authorities: ["/usr/share/filebeat/certs/ca/ca.crt"]

setup.kibana:
  host: "http://kibana:5601"
  username: elastic
  password: "${ELASTIC_PASSWORD}"
  protocol: "http"
  ssl.enabled: false
  ssl.certificate_authorities: ["/usr/share/filebeat/certs/ca/ca.crt"]
